bot:
  # 账号
  account: 1284700603
  # 密码
  password:
  loginmethod: qrcode
group_codes:
  - 852485822 # csgo
  - 1007452144
save_token: true
elastic: false
modules:
  manage:
    clear: "0 0 * * *"
    send: "00 19 * * *"
    notify_groups:
      - 852485822
    emby: http://emby.yangruoqi.site:8096
    emby_token: 907edf3821ca42528c775f69435fcbec
    spam_duration: 60s
    spam_msgs: 20
    spam_threshold: 0.8
    mute_duration: 1m
    keyword_reply:
      "(csgo服务器|(csgo)?社区服)": "控制台: connect csgo.yangruoqi.site; password bailan"
      "(mc|minecraft)服务器": "多人游戏: mc.yangruoqi.site，无密码，mod文件在群文件里"
      "(ts|teamspeak)服务器": "119.23.142.1，服务器问题联系@s1mple"
    files:
      "ts": {url: "https://files.teamspeak-services.com/releases/client/3.5.6/TeamSpeak3-Client-win64-3.5.6.exe", msg: "使用安装包安装TS"}
      "buding": {url: "https://github.com/jitingcn/TS3-Translation_zh-CN/releases/download/snapshot/Chinese_Translation_zh-CN.ts3_translation", msg: "装好TS客户端，再双击安装补丁"}
  roll:
    group_notice: false
    at_all: false
    recall: false
    addr: ":8083"
    rate:
      duration: 10m
      times: 3
  erotic:
    url: "https://api.lolicon.app/setu/v2"