bot:
  # 账号
  account: 1562167435
  # 密码
  password:
  loginmethod: qrcode
group_codes:
  - 852485822 # csgo
save_token: true
admin: 
  - 1284700603
  - 2935130658
modules:
  manage:
    clear: "0 0 * * *"
    send: "00 19 * * *"
    notify_groups:
      - 852485822
    emby: http://emby.yangruoqi.site:8096
    emby_token: 907edf3821ca42528c775f69435fcbec
    message_cache_time: 1m
    approve_friend_request: true
    keyword_reply:
      "(csgo服务器|(csgo)?社区服)": "控制台: connect csgo.yangruoqi.site; password bailan"
      "(mc|minecraft|Minecraft)服务器": "多人游戏: mc.yangruoqi.site，无密码，mod文件在群文件里"
      "(ts|teamspeak)服务器": "119.23.142.1，服务器问题联系@s1mple"
      "(方舟仙境|方舟维京|方舟|方舟服务器)": "182.61.17.105:27015，密码bailan"
      '(kali|群主|Kali)\s*(steam)?(好友)?代码' : "代码是1256694414"
      '小牛(冲冲)?\s*(steam)?(好友)?代码' : '代码是1129710459'
    files:
      "ts": {url: "https://files.teamspeak-services.com/releases/client/3.5.6/TeamSpeak3-Client-win64-3.5.6.exe", msg: "使用安装包安装TS"}
      "ts中文补丁": {url: "https://github.com/jitingcn/TS3-Translation_zh-CN/releases/download/snapshot/Chinese_Translation_zh-CN.ts3_translation", msg: "装好TS客户端，再双击安装补丁"}
    private_chat_list:
      - 1284700603 # 冲冲
      - 3560037068 # 仔仔
      - 3378410031 # 黑给
      - 2274731141 # 一纸虚无
      - 3063222036 # 加菲猫
      - 406583320 # 迪迦
      - 2935130658 # Kali
      - 727229837 # s1mple
      - 3417858507 # 吴彦祖
      - 1528779187 # 顺遂
      - 624918326 # 老张
      - 1577992396 # 彩虹马
      - 2778706039 # 四叶
      - 1733469675 # 翔子
      - 2498879160 # 阿拉斯托
  roll:
    group_notice: false
    at_all: false
    recall: false
    addr: ":8083"
    rate:
      duration: 10m
      times: 3
  erotic:
    url: "https://api.lolicon.app/setu/v2"
  spam:
    guard_duration: 60s # 在过去60s内
    allow: 10 # 放行成员的X条消息
    spam_threshold: 0.9 # 在第X+1条消息，触发antispam，检查最近的allow条消息，超过0.8时，封禁
    mute_duration: 1m # 1分钟
    mute_multiplier: 2 # 之后每一次触发封禁,提高一倍封禁时间
