version: '3'
services:
  robot:
    container_name: "qq-bot-instance"
    working_dir: "/etc/bot"
    volumes:
      - "/home/xlc1/bot-config:/etc/bot/config"
    ports:
      - "8083:8083"
    environment:
      TZ: "Asia/Shanghai"
      http_proxy: http://172.17.0.1:7890
      https_proxy: http://172.17.0.1:7890
      MONGO_URI: mongodb+srv://martin:ByyYSSEieTnSuD6k@cluster0.wvjww.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
      MONGO_PROXY: 172.17.0.1:7890
      QQ_GROUP_WELCOME_URI: https://s1.ax1x.com/2022/05/17/O4zLAU.png
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        http_proxy: "http://172.17.0.1:7890"
        https_proxy: "http://172.17.0.1:7890"
