version: '3'
services:
  robot:
    image: yangrq1018/bot-qq
    container_name: "qq-bot-instance"
    volumes:
      - "/home/xlc1/bot-config:/config"
    ports:
      - "8083:8083"
    environment:
      TZ: "Asia/Shanghai"
      http_proxy: http://172.17.0.1:7890
      https_proxy: http://172.17.0.1:7890
      MONGO_URI: mongodb://qqbot:qqbot@39.108.10.209:27017/?authMechanism=SCRAM-SHA-1&authSource=qq
      MONGO_PROXY: 172.17.0.1:7890
      QQ_GROUP_WELCOME_URI: https://s1.ax1x.com/2022/05/17/O4zLAU.png
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        http_proxy: "http://172.17.0.1:7890"
        https_proxy: "http://172.17.0.1:7890"
